### ISSUE TITLE
How do I use bencher for multiple files in benches/ ?

### ISSUE THREAD

**Issue by gnzlbg** [bluss/bencher#6]
In my Cargo.toml i have:

```toml
[[bench]] 
name = "..."
``` 

but i can use this only for a single file. How do I add more files (or all files in `/benches` automatically?).
